version: '2'
services:
  smile_footwear_api:
    image: khunpyaephyoaung/smile-footwear-api-smile
    ports:
      - 3500:3500
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./pre_sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_DATABASE=smile_footwear